name: Terraform Apply

on:
  workflow_call:
    inputs:
      TERRAFORM_PROJECT:
        type: string
        required: true
      ENV:
        type: string
        required: true
      BRANCH:
        type: string
        required: true
    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  terraform:
    name: "Deploy"
    runs-on: ubuntu-latest

     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

     # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        # terraform_version: 0.13.0:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Applies the configuration. This step will only run when a commit is pushed to BRANCH
    - name: Terraform Apply
      if: github.ref == 'refs/heads/${{ inputs.BRANCH }}' && github.event_name == 'push'
      run: |
        echo ${{ inputs.BRANCH }}
        export TF_WORKSPACE="${{ inputs.TERRAFORM_PROJECT }}-${{ inputs.ENV }}"
        cp variables/${{ inputs.ENV }}.auto.tfvars ./
        terraform apply -auto-approve
